#ifndef UCONFIGFILE_METADATA_H
#define UCONFIGFILE_METADATA_H

#define UCONFIG_METADATA_KEY_FILENAME   "filename"
#define UCONFIG_METADATA_KEY_FILETYPE   "filetype"

#define UCONFIG_METADATA_VALUE_RAWFILE  "raw"
#define UCONFIG_METADATA_VALUE_INIFILE  "winini"

#endif // UCONFIGFILE_METADATA_H
