#ifndef UCONFIGFILE_METADATA_H
#define UCONFIGFILE_METADATA_H

#define UCONFIG_METADATA_KEY_FILENAME   "filename"
#define UCONFIG_METADATA_KEY_FILETYPE   "filetype"
#define UCONFIG_METADATA_KEY_ROWDELIM   "2d-table/row-delimiter"
#define UCONFIG_METADATA_KEY_COLDELIM   "2d-table/column-delimiter"

#define UCONFIG_METADATA_VALUE_RAWFILE  "raw"
#define UCONFIG_METADATA_VALUE_INIFILE  "winini"
#define UCONFIG_METADATA_VALUE_2DTABLE  "2d-table"

#endif // UCONFIGFILE_METADATA_H
